### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by kabo** [bitnami/bitnami-docker-sonarqube#12]
**Description**

I'm unable to get the docker container running.

**Steps to reproduce the issue:**

1. 
    ```
    docker network create sonarqube-tier
    ```
2. 
    ```
    docker run --name postgresql \
     -e ALLOW_EMPTY_PASSWORD=no \
     -e POSTGRESQL_PASSWORD=qCkrK3BWf159pbcl70Byp0WEsNBwCZL2hkykj1qlPoFFYrjyUVmS27nSnv0BU8nd \
     --net sonarqube-tier \
     bitnami/postgresql:11-debian-9
    ```
3. 
    ```
    docker run \
      -e POSTGRESQL_HOST=postgresql \
      -e POSTGRESQL_ROOT_USER=postgres \
      -e POSTGRESQL_ROOT_PASSWORD=qCkrK3BWf159pbcl70Byp0WEsNBwCZL2hkykj1qlPoFFYrjyUVmS27nSnv0BU8nd \
      -e POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=sq \
      -e POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=sq \
      -e POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=dRmv5TuDHJbuM8pQBP3qle22tW5nd6OsIOpXkXOMHkoOTTA8NjMzeg4OM0vWqXh0 \
      -e SONARQUBE_DATABASE_USER=sq \
      -e SONARQUBE_DATABASE_NAME=sq \
      -e SONARQUBE_DATABASE_PASSWORD=dRmv5TuDHJbuM8pQBP3qle22tW5nd6OsIOpXkXOMHkoOTTA8NjMzeg4OM0vWqXh0 \
      -e ALLOW_EMPTY_PASSWORD=no \
      -e NAMI_LOG_LEVEL=trace \
     --net sonarqube-tier \
      bitnami/sonarqube:7-debian-9
    ```

**Describe the results you received:**

```
Welcome to the Bitnami sonarqube container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues

nami    INFO  Initializing postgresql-client
postgre DEBUG Waiting for service at postgresql:5432...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre TRACE [canConnect] Testing connection with 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'postgres' user is successful
postgre INFO  PostgreSQL server listening and working at postgresql:5432
postgre TRACE [canConnect] Testing connection with 'sq' user
postgre TRACE [showDatabases] Getting databases for 'sq' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Usq,-cSELECT datname FROM pg_database;
postgre ERROR [canConnect] Connection with 'sq' user is unsuccessful
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT rolname FROM pg_roles
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT 1 FROM pg_roles WHERE rolname='sq'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cCREATE USER "sq" PASSWORD '765yiU0Y44GzLJNoT8ys6ZeagI1ClRO7Ni76EN1UiHeiGg9XKcMMdaxl2f9NfhSn'
postgre TRACE [existsDatabase] Checking database existance for 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n template1\n template0\n\n"
postgre INFO  ==> Creating database sq...
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT 1 FROM pg_database WHERE datname='sq'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cCREATE DATABASE sq
postgre INFO  ==> Granting access to sq to the database sq...
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dsq,-Upostgres,-cGRANT ALL PRIVILEGES ON DATABASE "sq" TO "sq"
nami    INFO  postgresql-client successfully initialized
nami    INFO  Initializing sonarqube
sonarqu DEBUG ==> Creating SonarQube System User...
sonarqu INFO  ==> Creating server folders...
sonarqu INFO  ==> Configuring database parameters...
sonarqu INFO  ==> Configuring server parameters...
sonarqu INFO  ==> Configure permissions...
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/data
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/temp
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/logs
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/extensions
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/pids
sonarqu INFO  ==> Initializing SonarQube from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre TRACE [canConnect] Testing connection with 'sq' user
postgre TRACE [showDatabases] Getting databases for 'sq' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Usq,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n template1\n template0\n sq\n\n"
postgre TRACE [canConnect] Connection with 'sq' user is successful
postgre INFO  PostgreSQL server listening and working at postgresql:5432
sonarqu INFO  ==> Starting app...
sonarqu TRACE [runProgram] Executing: null su - sonarqube -c 'PATH=/opt/bitnami/java/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/java/bin:/opt/bitnami/sonarqube/bin/linux-x86-64/:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/bitnami/sonarqube/bin/linux-x86-64/sonar.sh start'
sonarqu TRACE code: 0
sonarqu TRACE stdout:

sonarqu TRACE stderr:

sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.
Error executing 'postInstallation': Log entry not found after 300 s.
nami    TRACE Error: Error executing 'postInstallation': Log entry not found after 300 s.
    at Object.waitForEntry (/root/.nami/components/com.bitnami.sonarqube/lib/log.js:33:41)
    at Object.$app.helpers.waitForLogEntry (/root/.nami/components/com.bitnami.sonarqube/helpers.js:86:18)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.sonarqube/main.js:61:18)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
    at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
```

**Describe the results you expected:**

The docker container to start normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:56 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 23
 Server Version: 19.03.1
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-5-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.58GiB
 Name: esk
 ID: NFZQ:ZPFD:V3Z2:BKQQ:CNZ6:KGMI:R4CV:4TZG:M3ST:DXBR:A7AM:DJ7V
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by kabo** [comment]
Tried again after downgrading docker by running
```
sudo apt install docker-ce=5:18.09.8~3-0~debian-buster docker-ce-cli=5:18.09.8~3-0~debian-buster
```

Same result though.

**Comment by juan131** [comment]
Hi @kabo 

I was unable to reproduce your issue following the same steps. Here you can find that I didn't find the error you faced:

```
sonarqu INFO  ==> Starting app...
sonarqu TRACE [runProgram] Executing: null su - sonarqube -c 'PATH=/opt/bitnami/java/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/java/bin:/opt/bitnami/sonarqube/bin/linux-x86-64/:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/bitnami/sonarqube/bin/linux-x86-64/sonar.sh start'
sonarqu TRACE code: 0
sonarqu TRACE stdout:

sonarqu TRACE stderr:

sonarqu INFO  ==> Configuring username...
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dsq,-Usq,-cUPDATE users SET login='admin'
sonarqu INFO  ==> Configuring salt and password...
```

Could you access (`docker exec...`) the container while it's initializing Sonarqube and check the content of the log file (`cat /opt/bitnami/sonarqube/logs/sonar.log`)? We might get more information from the logs

**Comment by kabo** [comment]
```
root@d0ee5ef3d6a8:~# cat /opt/bitnami/sonarqube/logs/sonar.log
--> Wrapper Started as Daemon
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2019.08.06 09:39:43 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/bitnami/sonarqube/temp
2019.08.06 09:39:43 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.08.06 09:39:43 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/bitnami/sonarqube/elasticsearch]: /opt/bitnami/sonarqube/elasticsearch/bin/elasticsearch
2019.08.06 09:39:43 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.08.06 09:39:44 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.08.06 09:39:44 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
2019.08.06 09:40:01 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 78
2019.08.06 09:40:01 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.08.06 09:40:01 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
```

**Comment by kabo** [comment]
I had a read through this thread
https://github.com/SonarSource/docker-sonarqube/issues/282

After running
```
sysctl -w vm.max_map_count=262144
sudo systemctl restart docker
```
it starts up!

But I want to run this image in AWS Fargate... I'm not aware of any way to run that sysctl call in AWS Fargate.

This guy seems to have found a way around it: https://github.com/SonarSource/docker-sonarqube/issues/282#issuecomment-508507407

Any ideas on how I can achieve that with this image please?

**Comment by juan131** [comment]
Hi @kabo 

I guess we could implement some kind of env. variable that allows us to define the maximum number of open file descriptors. We did something similar in the past on some charts such as RabbitMQ (see `rabbitmq.setUlimitNofiles` and `rabbitmq.ulimitNofiles` parameters at https://github.com/helm/charts/blob/master/stable/rabbitmq/README.md)

I'm not an expert in **AWS Fargate** but according to the link you shared it seems you can define the ulimits in the ECS task definition.

**Comment by kabo** [comment]
The ulimit is fine, I was referring to point 2:

![Screenshot from 2019-08-07 08-46-32](https://user-images.githubusercontent.com/357601/62575929-4f2fac00-b88b-11e9-8f96-d5f337229a40.png)

**Comment by kabo** [comment]
Tried adding `-e SONARQUBE_JAVA_OPTS="node.store.allow_mmapfs=false"` or `-e SONARQUBE_JAVA_OPTS="-Dnode.store.allow_mmapfs=false"` or `-e SONARQUBE_JAVA_OPTS="-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmapfs=false"`, no difference.

**Comment by kabo** [comment]
If I run this locally:
```
docker run \
<...snip...>
  --net sonarqube-tier \
  --entrypoint "" -it \
  bitnami/sonarqube:7-debian-9 /bin/bash
```
I get a bash terminal.
If I then run
```
sed s/#sonar.search.javaAdditionalOpts=/sonar.search.javaAdditionalOpts=-Dnode.store.allow_mmapfs=false/ /opt/bitnami/sonarqube/conf/sonar.properties -i
/app-entrypoint.sh nami start --foreground sonarqube
```
Sonarqube starts up fine.

**Comment by kabo** [comment]
`docker run` with `-e SONARQUBE_JAVA_OPTS="-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmapfs=false"` doesn't seem to be passing on the `SONARQUBE_JAVA_OPTS`.
I ran `ps -ef` in the container
```
root@fb0620fed91f:/# ps -ef | cat
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 01:02 pts/0    00:00:00 /bin/bash
root         6     0  0 01:02 pts/1    00:00:00 /bin/bash
root        13     1  0 01:02 pts/0    00:00:00 /bin/bash -e /app-entrypoint.sh nami start --foreground sonarqube
root        55    13 31 01:03 pts/0    00:00:02 /opt/bitnami/nami/runtime/node --max_semi_space_size=150 --stack_size=16000 /opt/bitnami/nami/index.js initialize sonarqube --inputs-file=/sonarqube-inputs.json
sonarqu+   149     1  0 01:03 ?        00:00:00 /opt/bitnami/sonarqube/bin/linux-x86-64/./wrapper /opt/bitnami/sonarqube/bin/linux-x86-64/../../conf/wrapper.conf wrapper.syslog.ident=SonarQube wrapper.pidfile=/opt/bitnami/sonarqube/pids/SonarQube.pid wrapper.daemonize=TRUE
sonarqu+   151   149 99 01:03 ?        00:00:08 java -Dsonar.wrapped=true -Djava.awt.headless=true -Xms8m -Xmx32m -Djava.library.path=./lib -classpath ../../lib/jsw/wrapper-3.2.3.jar:../../lib/common/netty-codec-4.1.32.Final.jar:../../lib/common/netty-codec-http-4.1.32.Final.jar:../../lib/common/netty-common-4.1.32.Final.jar:../../lib/common/netty-handler-4.1.32.Final.jar:../../lib/common/netty-resolver-4.1.32.Final.jar:../../lib/common/netty-transport-4.1.32.Final.jar:../../lib/common/okhttp-3.14.2.jar:../../lib/common/okio-1.17.2.jar:../../lib/common/parent-join-client-6.8.0.jar:../../lib/common/percolator-client-6.8.0.jar:../../lib/common/picocontainer-2.15.jar:../../lib/common/protobuf-java-3.7.0.jar:../../lib/common/slf4j-api-1.7.25.jar:../../lib/common/snakeyaml-1.17.jar:../../lib/common/sonar-ce-7.9.1.jar:../../lib/common/sonar-ce-common-7.9.1.jar:../../lib/common/sonar-ce-task-7.9.1.jar:../../lib/common/sonar-ce-task-projectanalysis-7.9.1.jar:../../lib/common/sonar-channel-4.1.jar:../../lib/common/sonar-check-api-7.9.1.jar:../../lib/common/sonar-classloader-1.0.jar:../../lib/common/sonar-core-7.9.1.jar:../../lib/common/sonar-db-core-7.9.1.jar:../../lib/common/sonar-db-dao-7.9.1.jar:../../lib/common/sonar-db-migration-7.9.1.jar:../../lib/common/sonar-duplications-7.9.1.jar:../../lib/common/sonar-main-7.9.1.jar:../../lib/common/sonar-markdown-7.9.1.jar:../../lib/common/sonar-plugin-api-7.9.1-all.jar:../../lib/common/sonar-plugin-api-7.9.1.jar:../../lib/common/sonar-process-7.9.1.jar:../../lib/common/sonar-scanner-protocol-7.9.1.jar:../../lib/common/sonar-server-7.9.1.jar:../../lib/common/sonar-server-common-7.9.1.jar:../../lib/common/sonar-update-center-common-1.18.0.487.jar:../../lib/common/sonar-ws-7.9.1.jar:../../lib/common/stax2-api-3.1.4.jar:../../lib/common/staxmate-2.0.1.jar:../../lib/common/t-digest-3.2.jar:../../lib/common/tomcat-annotations-api-8.5.38.jar:../../lib/common/tomcat-embed-core-8.5.38.jar:../../lib/common/transport-6.8.0.jar:../../lib/common/transport-netty4-client-6.8.0.jar:../../lib/common/woodstox-core-lgpl-4.4.0.jar:../../lib/common/HdrHistogram-2.1.9.jar:../../lib/common/activation-1.1.jar:../../lib/common/commons-codec-1.12.jar:../../lib/common/commons-csv-1.4.jar:../../lib/common/commons-dbcp2-2.5.0.jar:../../lib/common/commons-dbutils-1.5.jar:../../lib/common/commons-email-1.5.jar:../../lib/common/commons-io-2.6.jar:../../lib/common/commons-lang-2.6.jar:../../lib/common/commons-logging-1.2.jar:../../lib/common/commons-pool2-2.6.0.jar:../../lib/common/diffutils-1.2.jar:../../lib/common/elasticsearch-6.8.0.jar:../../lib/common/elasticsearch-cli-6.8.0.jar:../../lib/common/elasticsearch-core-6.8.0.jar:../../lib/common/elasticsearch-secure-sm-6.8.0.jar:../../lib/common/elasticsearch-x-content-6.8.0.jar:../../lib/common/gson-2.8.4.jar:../../lib/common/guava-18.0.jar:../../lib/common/hazelcast-3.8.6.jar:../../lib/common/hazelcast-client-3.8.6.jar:../../lib/common/hppc-0.7.1.jar:../../lib/common/httpclient-4.5.2.jar:../../lib/common/httpcore-4.4.4.jar:../../lib/common/jackson-annotations-2.9.8.jar:../../lib/common/jackson-core-2.9.8.jar:../../lib/common/jackson-databind-2.9.8.jar:../../lib/common/jackson-dataformat-cbor-2.8.11.jar:../../lib/common/jackson-dataformat-smile-2.8.11.jar:../../lib/common/jackson-dataformat-yaml-2.8.11.jar:../../lib/common/javax.mail-1.5.6.jar:../../lib/common/jaxb-api-2.3.0.jar:../../lib/common/jbcrypt-0.4.jar:../../lib/common/jjwt-api-0.10.5.jar:../../lib/common/jjwt-impl-0.10.5.jar:../../lib/common/jjwt-jackson-0.10.5.jar:../../lib/common/jna-4.5.1.jar:../../lib/common/joda-time-2.10.1.jar:../../lib/common/jopt-simple-5.0.2.jar:../../lib/common/jul-to-slf4j-1.7.25.jar:../../lib/common/log4j-api-2.8.2.jar:../../lib/common/log4j-to-slf4j-2.8.2.jar:../../lib/common/logback-access-1.2.3.jar:../../lib/common/logback-classic-1.2.3.jar:../../lib/common/logback-core-1.2.3.jar:../../lib/common/lucene-analyzers-common-7.7.0.jar:../../lib/common/lucene-backward-codecs-7.7.0.jar:../../lib/common/lucene-core-7.7.0.jar:../../lib/common/lucene-grouping-7.7.0.jar:../../lib/common/lucene-highlighter-7.7.0.jar:../../lib/common/lucene-join-7.7.0.jar:../../lib/common/lucene-memory-7.7.0.jar:../../lib/common/lucene-misc-7.7.0.jar:../../lib/common/lucene-queries-7.7.0.jar:../../lib/common/lucene-queryparser-7.7.0.jar:../../lib/common/lucene-sandbox-7.7.0.jar:../../lib/common/lucene-spatial-7.7.0.jar:../../lib/common/lucene-spatial-extras-7.7.0.jar:../../lib/common/lucene-spatial3d-7.7.0.jar:../../lib/common/lucene-suggest-7.7.0.jar:../../lib/common/lz4-1.3.0.jar:../../lib/common/mybatis-3.5.1.jar:../../lib/common/nanohttpd-2.3.0.jar:../../lib/common/netty-buffer-4.1.32.Final.jar:../../lib/sonar-application-7.9.1.jar:../../lib/sonar-shutdowner-7.9.1.jar -Dwrapper.key=8ZH2yVRhToyVaQec -Dwrapper.port=32000 -Dwrapper.jvm.port.min=31000 -Dwrapper.jvm.port.max=31999 -Dwrapper.pid=149 -Dwrapper.version=3.2.3 -Dwrapper.native_library=wrapper -Dwrapper.service=TRUE -Dwrapper.cpu.timeout=10 -Dwrapper.jvmid=1 org.tanukisoftware.wrapper.WrapperSimpleApp org.sonar.application.App
sonarqu+   186   151 99 01:03 ?        00:00:05 /opt/bitnami/java/bin/java -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=/opt/bitnami/sonarqube/temp -XX:ErrorFile=../logs/es_hs_err_pid%p.log -Des.enforce.bootstrap.checks=true -Xms512m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/opt/bitnami/sonarqube/elasticsearch -Des.path.conf=/opt/bitnami/sonarqube/temp/conf/es -Des.distribution.flavor=default -Des.distribution.type=tar -cp /opt/bitnami/sonarqube/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch
```

No sign of `-Dsonar.search.javaAdditionalOpts` or `Dnode.store.allow_mmapfs=false` :/

**Comment by juan131** [comment]
Hi @kabo 

Correct me if I'm wrong but you're just requesting a way to add your own custom java options, aren't you?

I was able to reproduce your issue I could check the env. variable **SONARQUBE_JAVA_OPTS** is not working as expected. I was able to add the option using the workaround below:

```console
$ docker-compose up -d
$ docker-compose exec sonarqube bash
# sed -i -e 's/#sonar.search.javaAdditionalOpts=/sonar.search.javaAdditionalOpts=-Dnode.store.allow_mmapfs=false/g' /opt/bitnami/sonarqube/conf/sonar.properties
# sudo nami restart sonarqube
```

**Comment by kabo** [comment]
Yes, if `SONARQUBE_JAVA_OPTS` would work as expected I think this could run on AWS Fargate. Would be great if you could look into that, thanks!

**Comment by juan131** [comment]
Hi @kabo 

I just created a task to work on fixing this env. variable. I hope to be able to work on this during this week. I'll keep you updated and let you know when we release a new version of the image fixing it

Thanks so much for reporting the issue!

**Comment by juan131** [comment]
Hi @kabo 

We just release a new revision of the image (**7.9.1-r29**) that accepts the env. variables below (see https://github.com/bitnami/bitnami-docker-sonarqube#configuration):
 
- SONARQUBE_CE_JAVA_ADD_OPTS
- SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS
- SONARQUBE_WEB_JAVA_ADD_OPTS

Could you try to use those env. variable to modify the Java options used?

**Comment by kabo** [comment]
OK, cool, that works!

Next error:
```
sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.
```

Looking at `/opt/bitnami/sonarqube/logs/web.log` it is in the process of running DbMigrations when it reaches the timeout. Last entries are:

```
...
2019.08.10 04:57:26 INFO  web[][o.s.s.p.d.m.s.MassUpdate] 1 Users with System Administer permission as root processed (0 items/sec)
2019.08.10 04:57:27 INFO  web[][DbMigrations] #1405 'Populate column USERS.IS_ROOT': success | time=3323ms
2019.08.10 04:57:27 INFO  web[][DbMigrations] #1406 'Make column USERS.IS_ROOT not nullable'...
2019.08.10 04:57:29 INFO  web[][DbMigrations] #1406 'Make column USERS.IS_ROOT not nullable': success | time=1515ms
2019.08.10 04:57:29 INFO  web[][DbMigrations] #1407 'Populate column GROUPS.ORGANIZATION_UUID'...
```

Is there any way of extending that timeout beyond 300 seconds?

**Comment by kabo** [comment]
I got it going, I ran it closer to the DB. Still would be handy to be able to adjust the timeout though...

**Comment by kabo** [comment]
For reference, these are the important bits in my container definition in case anyone's wondering

```json
    "environment": [
      {
        "name": "SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS",
        "value": "-Dnode.store.allow_mmapfs=false"
      }
    ],
    "ulimits": [
      {
        "name": "nofile",
        "softLimit": 65535,
        "hardLimit": 65535
      }
    ]
```

**Comment by juan131** [comment]
Thanks for sharing the task definition @kabo !!
Regarding the issue with the timeout, could we open a different issue to discuss there? just to avoid mixing topics under the same issue thread.

**Comment by kimeirik-bym** [comment]
> For reference, these are the important bits in my container definition in case anyone's wondering
> 
> ```json
>     "environment": [
>       {
>         "name": "SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS",
>         "value": "-Dnode.store.allow_mmapfs=false"
>       }
>     ],
> ```

This property has been renamed according to a recent error message:
```
2022.06.15 09:00:24 ERROR app[][o.s.a.p.ManagedProcessHandler] Failed to launch process [ElasticSearch]
org.sonar.process.MessageException: Property 'node.store.allow_mmapfs' is no longer supported. Use 'node.store.allow_mmap' instead.
```

So for anyone wondering why it's stuck at "==> Waiting for SonarQube to start..." in Fargate even after applying this, try changing the property:
```json
    "environment": [
      {
        "name": "SONARQUBE_ELASTICSEARCH_JAVA_ADD_OPTS",
        "value": "-Dnode.store.allow_mmap=false"
      }
    ],
```
