### ISSUE TITLE
postInstall hangs

### ISSUE THREAD

**Issue by BoKKeR** [bitnami/bitnami-docker-sonarqube#22]
**Description**
Trying to run on unraid, mounted a volume for /sonarqube_data

**Steps to reproduce the issue:**

1. Setup postgres11 container
2. setup sonarqube container on unraid 
3. logs show that there is a postgres connection.
4. logs stop as the postInstall hangs
5. No files get created in volume folder
6. same result when running without volume folder

logs stop as the postInstall hangs after
sonarqu INFO ==> Starting app...

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.5, build 633a0ea838
```

- Output of `docker info`:

```
nami INFO Initializing postgresql-client
nami INFO postgresql-client successfully initialized
nami INFO Initializing sonarqube
sonarqu DEBUG ==> Creating SonarQube System User...
sonarqu INFO ==> Creating server folders...
sonarqu INFO ==> Configuring database parameters...
sonarqu INFO ==> Configuring server parameters...
sonarqu INFO ==> Configure permissions...
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/data
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/temp
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/logs
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/extensions
sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/pids
sonarqu INFO ==> Initializing SonarQube from scratch...
postgre INFO Trying to connect to PostgreSQL server
postgre INFO Found PostgreSQL server listening at 10.0.0.168:5432
postgre TRACE [canConnect] Testing connection with 'bn_sonarqube' user
postgre TRACE [showDatabases] Getting databases for 'bn_sonarqube' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-h10.0.0.168,-dbitnami_sonarqube,-Ubn_sonarqube,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n bitnami_sonarqube\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'bn_sonarqube' user is successful
postgre INFO PostgreSQL server listening and working at 10.0.0.168:5432
sonarqu INFO ==> Starting app...
sonarqu TRACE [runProgram] Executing: null su - sonarqube -c 'PATH=/opt/bitnami/java/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/java/bin:/opt/bitnami/common/bin:/opt/bitnami/sonarqube/bin/linux-x86-64/:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/bitnami/sonarqube/bin/linux-x86-64/sonar.sh start'
sonarqu TRACE code: 0
sonarqu TRACE stdout:

sonarqu TRACE stderr:

sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.

Error executing 'postInstallation': Log entry not found after 300 s.

nami TRACE Error: Error executing 'postInstallation': Log entry not found after 300 s.

at Object.waitForEntry (/root/.nami/components/com.bitnami.sonarqube/lib/log.js:33:41)
at Object.$app.helpers.waitForLogEntry (/root/.nami/components/com.bitnami.sonarqube/helpers.js:92:18)
at Service.$app.postInstallation (/root/.nami/components/com.bitnami.sonarqube/main.js:64:18)
at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 300 s.

Error executing 'postInstallation': Log entry not found after 300 s.

nami TRACE Error: Error executing 'postInstallation': Log entry not found after 300 s.

at Object.waitForEntry (/root/.nami/components/com.bitnami.sonarqube/lib/log.js:33:41)
at Object.$app.helpers.waitForLogEntry (/root/.nami/components/com.bitnami.sonarqube/helpers.js:92:18)
at Service.$app.postInstallation (/root/.nami/components/com.bitnami.sonarqube/main.js:64:18)
at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
```

- Output of `docker-compose version` (if applicable):

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='sonarqube' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'SONARQUBE_DATABASE_USER'='xxx' -e 'SONARQUBE_DATABASE_NAME'='xxx' -e 'SONARQUBE_DATABASE_PASSWORD'='xxx' -e 'POSTGRESQL_HOST'='10.0.0.168' -e 'POSTGRESQL_ROOT_USER'='xxx' -e 'POSTGRESQL_ROOT_PASSWORD'='xxx' -e 'POSTGRESQL_PORT_NUMBER'='5432' -e 'NAMI_LOG_LEVEL'='trace' -p '9000:80/tcp' 'bitnami/sonarqube' 
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate if the unraid device is ARM or x86_64 ?
  Our containers only run on x86_64 architectures.

**Comment by BoKKeR** [comment]
X86_64, its a intel 8700k

**Comment by rafariossaa** [comment]
Can you retry ?
I have found it not always start at the first try.
I am opening an internal task to look deeper into this issue.

**Comment by rafariossaa** [comment]
Hi @BoKKeR ,
  Could you take a look to this other thread ? https://github.com/bitnami/bitnami-docker-sonarqube/issues/21
  It seems very similar to your issue.

**Comment by BoKKeR** [comment]
Thanks that solved my issue. 
Running `cat /opt/bitnami/sonarqube/logs/es.log` revealed the cause was the same. 
Would be nice to have it included in the container output
